import { Raleway } from 'next/font/google';
import { Tilt_Neon } from 'next/font/google';
import "./globals.css";

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
});

 export const tiltNeon = Tilt_Neon({
  subsets: ['latin'],
  weight: ['400'], 
});

// export const metadata = {
//   title: "WS",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} font-raleway antialiased`}>
        {children}
      </body>
    </html>
  );
}
